Output clu_demo.gif

Set Height 600
Source config.tape

Type `clu`
Enter
Sleep 5s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500s
Up
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 2s
Type "/"
Sleep 1.5s
Type "pfb"
Sleep 500ms
Down
Sleep 2s
Tab
Sleep 2s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 2s
Tab
Sleep 2s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 2s
Tab
Sleep 2s
Type "/"
Backspace 3
Sleep 5s
Type "q"