Output clu_demo.gif

Set Height 600
Source config.tape

Type `clu`
Enter
Sleep 6s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 1s
Type "/pfb"
Sleep 500ms
Down
Sleep 2s
Tab
Sleep 2s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 1s
Tab
Sleep 2s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 500ms
Up
Sleep 1s
Tab
Sleep 2s
Type "/"
Backspace 3
Sleep 2s
Type "q"